export default {
  SET_EXPRESSION: 'SET_EXPRESSION',
  CLEAR_EXPRESSION: 'CLEAR_EXPRESSION',
  DELETE_LAST_EXPRESSION_ENTRY: 'DELETE_LAST_EXPRESSION_ENTRY',
  EVALUATE_EXPRESSION: 'EVALUATE_EXPRESSION',
  SQRT_EXPRESSION: 'SQRT_EXPRESSION',
  EXPONENTIATION_EXPRESSION: 'EXPONENTIATION_EXPRESSION'
};